config/routes.rb
Rails.application.routes.draw do

  root 'page#index'

  get 'vdm' => 'page#vdm'

  mount Vdm::Base => '/'

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :content, :date, :author

  # Filter the result according to the parameters
  def self.filter(attributes)
    attributes.reduce(all) do |scope, (key, value)|
      return scope if value.blank?
      case key.to_sym
      when :author # direct search
        scope.where(key => value)
      when :from
        scope.where("date > ?", value)
      when :to
        scope.where("date < ?", value)
      else # unknown key (do nothing or raise error, as you prefer to)
        scope
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  # This is our homepage
  def index
    @url_all    = "#{request.base_url}/api/v1/posts"
    @url_author = "#{request.base_url}/api/v1/posts?author=Anonyme"
    @url_date   = "#{request.base_url}/api/v1/posts?from=#{1.week.ago.to_date}"
    @url_full   = "#{request.base_url}/api/v1/posts?author=Anonyme&from=#{2.weeks.ago.to_date}&to=#{1.day.ago.to_date}"
  end

  # Get the 200 last posts from VDM
  def vdm
    # This is not a best practice to call a rake task inside the controller
    # This is just to demonstrate the behavior of the task
    %x[rake vdm:get_posts NB_OF_VDM_TO_GET=200]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/page/index.html.erb
<h1>This is my iAdvize Backend challenge</h1>

<h2>Get the posts</h2>
You can get the last X posts from VDM with this simple command line :<br />
<i>rake vdm:get_posts NB_OF_VDM_TO_GET=200</i><br /><br />

Or you can go to <%= link_to "#{request.base_url}/vdm", vdm_path, :id => "link" %> to get a preview of the result (this will execute the command).<br /><br />


<h2>Use the API</h2>
Please visit the API at <%= link_to @url_all, @url_all %><br />
This will give you all the posts in JSON. You can use optionals parameters (from, to, author).<br /><br />

<ul>
  <li>Get all the posts : <%= link_to @url_all, @url_all %></li>
  <li>Get all the posts from Anonyme : <%= link_to @url_author, @url_author %></li>
  <li>Get all the posts from/to a date : <%= link_to @url_date, @url_date %></li>
  <li>Get all the posts from Anonyme between two dates : <%= link_to @url_full, @url_full %></li>
</ul>

<br />

<h2>Unit tests</h2>
There is multiple unit tests for the Post model and the API that can be run with the command <i>rake test</i>


<script>
  $(document).ready(function () {
    $('#link').click(function() {
      this.innerHTML = 'Wait for it...';
    });
  });
</script>

app/views/page/vdm.html.erb
<ol>
  <% Post.all.each do |vdm| %>
    <li><%= vdm.content %> | <%= vdm.date %> | <%= vdm.author %></li>
  <% end %>
</ol>